### ISSUE TITLE
chat gpt alert

### ISSUE THREAD

**Issue by MarvelcoOGFN** [optixyt0/Axis-Backend#1]
L bozo skid i hope lightning dies

**Comment by optixyt0** [comment]
Bro why do you care so much. What did I even do to you??

**Comment by FlashCoder2024** [comment]
> Bro why do you care so much. What did I even do to you??

this ChatGPT code is for real???

**Comment by optixyt0** [comment]
> > Bro why do you care so much. What did I even do to you??
> 
> 
> 
> this ChatGPT code is for real???

No. My friend @endlessalpacaYT literally watched me code this all, marv is accusing me of having a second monitor, I will happily show my setup

**Comment by FlashCoder2024** [comment]
> > > Bro why do you care so much. What did I even do to you??
> > 
> > 
> > this ChatGPT code is for real???
> 
> No. My friend @endlessalpacaYT literally watched me code this all, marv is accusing me of having a second monitor, I will happily show my setup

Do you have a second monitor?

**Comment by optixyt0** [comment]
No.

**Comment by optixyt0** [comment]
'skid' hahaha very funny. At least i tried to do something original.






---- On Sun, 13 Oct 2024 21:55:43 +0100 Marvelco ***@***.***> wrote ---





L bozo skid i hope lightning dies
